Added a few new goodies, and another attempt to fix the sound button (which worked this time!)
hackclub/high-seas pull request #1053
Opened 2024-12-30 16:51 UTC by barxilly

2024-12-30 16:52 UTC, barxilly commented
The thing I changed with the idea generator came from GPT refusing to make something that probably would be very hard

2024-12-31 04:22 UTC, Gitstar-OC requested changes
Hey update the commit after running `npx prettier run --write .`

2024-12-31 04:23 UTC, Gitstar-OC commented
@barxilly

2025-01-08 12:33 UTC, Gitstar-OC reviewed
Wait. I will make a commit in this, that will solve the prettify check!

2025-03-08 16:36 UTC, closed without merging