Add progress bar percentage display
hackclub/high-seas pull request #856
Opened 2024-11-24 21:06 UTC by 3kh0

This pull adds a few new words and phrases, improves the README a bit, and adds a percentage to the progress bar

2024-11-25 13:57 UTC, maxwofford commented
Please run the formatter provided with `bun fmt`! I think your editor is autoformatting the files you opened and changing stuff you don't mean to. Heads up, you probably never want to `git add --all` or commit whole file changes– check out `git add -p`.

2024-11-26 01:18 UTC, 3kh0 commented
@maxwofford Fixed!

2024-12-06 17:48 UTC, malted requested changes

2024-12-06 17:48 UTC, malted commented on README.md
> +bun run dev
Let's keep this as it was

2024-12-06 17:48 UTC, malted commented on lib/flavor.js
> +  'Pirate',
```suggestion
```

2024-12-06 17:48 UTC, malted commented on lib/flavor.js
> +  // "when you're richer...",
Have you tested this? We shortened these pretty aggressively because the buttons are so small

2024-12-06 17:48 UTC, malted commented on lib/flavor.js
> +  // "when you're richer...",
Repeated

```suggestion
```

2024-12-06 17:48 UTC, malted commented on lib/flavor.js
> +  // "when you're richer...",
![image](https://github.com/user-attachments/assets/df7772d7-de2d-4ac9-a042-ca37d4aa687e)

Case in point

2024-12-06 17:48 UTC, malted commented on src/app/harbor/shop/progress.tsx
> +          </div>
![image](https://github.com/user-attachments/assets/b8013031-5e14-404e-bca6-3fab9fd46dd7)

The reason this wasn't there before is that it's not just the *last* thing you're working towards, there are other things as well

I wonder if there's a way to make it consistent for all bookmarked items...

2024-12-14 05:57 UTC, closed without merging